Movies/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Movies import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls'), name='movie-app-index'),
    path(r'captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__', include('debug_toolbar.urls')),]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

movie_app/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from Movies import settings
from .views import *

app_name = 'movie_app'
urlpatterns = [
    path('', MovieList.as_view(), name='main'),
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('movie/<slug:slug_movie>', ShowMovie.as_view(), name='movie'),
    path('year/<int:year_movie>', MovieByYear.as_view(), name='year'),
    path('genre/<slug:slug_genre>', MovieByGenre.as_view(), name='genre'),
    path('rating/<int:rating>', MovieByRating.as_view(), name='rating'),
    path('genres/', GenreList.as_view(), name='genres'),
    path('add-movie/', AddMovie.as_view(), name='add-movie'),
    path('about/', about, name='about'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('contacts/', ContactFormView.as_view(), name='contact-us'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_app/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Movie(models.Model):
    title = models.CharField(max_length=255, verbose_name='Movie title')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    description = models.TextField()
    cover = models.ImageField(upload_to='covers/%Y/%m/%d')
    year = models.IntegerField()
    rating = models.IntegerField()
    genre = models.ManyToManyField('Genre')
    date_creation = models.DateTimeField(verbose_name='Creation date', auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'All movies'
        verbose_name_plural = 'All movies'
        ordering = ('title', 'year',)

    def __str__(self):
        return f'{self.title}, {self.year}'

    def get_absolute_url(self):
        return reverse('movie_app:movie', kwargs={'slug_movie': self.slug})

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_creation <= now


class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'
        ordering = ('name',)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('movie_app:genre', kwargs={'slug_genre': self.slug})


def auto_incrementor():
    last_int = MenuItem.objects.all().order_by('position').last()
    if not last_int:
        return 1
    return last_int.position + 1


class MenuItem(models.Model):
    title = models.CharField(max_length=128)
    slug = models.SlugField(max_length=155, unique=True, verbose_name='URL')
    position = models.PositiveIntegerField(default=auto_incrementor,)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ('position',)
        verbose_name = 'Menu item'
        verbose_name_plural = 'Menu items'


class ContactUsData(models.Model):
    name = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    email = models.EmailField()
    content = models.TextField()

    def __str__(self):
        return f'From {self.name}, {self.email};\nsubject:\n{self.subject}'

    class Meta:
        ordering = ('name',)
        verbose_name = 'Contact us message'
        verbose_name_plural = 'Contact us messages'


class Subscribe(models.Model):
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True, verbose_name='Is subscribed')
    date_subscribe = models.DateTimeField(auto_now_add=True, verbose_name='Subscribe date')
    date_unsubscribe = models.DateTimeField(null=True, verbose_name='Unsubscribe date')

    def __str__(self):
        return self.email

    class Meta:
        ordering = ('email',)
        verbose_name = 'Subscriber'
        verbose_name_plural = 'Subscribers'


class FavoriteMovie(models.Model):
    pass
    # TODO

movie_app/forms.py
import datetime

from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import *
from crispy_forms.helper import FormHelper


class AddMovieForm(forms.ModelForm):
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['genre'].empty_label = '< Choose genre(s) >'
        self.helper = FormHelper()

    class Meta:
        model = Movie
        fields = ['title', 'slug', 'description', 'year', 'cover', 'rating', 'genre']

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 255:
            raise ValidationError('Length is more than 255 symbols.')
        return title

    def clean_year(self):
        year = self.cleaned_data['year']
        now = datetime.datetime.now().year + 1
        if not 1878 >= year >= now:
            raise ValidationError(f'Year may be after 1878 and before {now} inclusive.')
        return year

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        if not 0 >= rating >= 100:
            raise ValidationError(f'Rating may be from 0 to 100.')
        return rating


class RegisterUserForm(UserCreationForm):
    captcha = CaptchaField()
    email = forms.CharField(max_length=255, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    def clean_email(self):
        email = self.cleaned_data['email']
        is_exists = User.objects.filter(email=email)
        if is_exists:
            raise ValidationError(f'User with email "{email}" already exists.')
        return email

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    class Meta:
        model = User


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    class Meta:
        model = ContactUsData
        fields = ['subject', 'content', 'name', 'email']


class SubscribeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    def clean_email(self):
        email = self.cleaned_data['email']
        is_exists = Subscribe.objects.filter(email=email)
        if is_exists:
            raise ValidationError(f'Your email "{email}" is already subscribed!')
        return email

    class Meta:
        model = Subscribe
        fields = ['email']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'newsletter',
                                            'onchange': 'this.form.submit()',
                                            'placeholder': 'Your email...'})
        }
        labels = {
            'email': ''
        }

movie_app/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.db.models import Count
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django_filters.views import FilterView

from .filters import MovieFilter
from .models import *
from .forms import *
from .utils import *

titles = {
    'main': 'All movies',
    'add-movie': 'Add movie',
    'about': 'About',
    'login': 'Log in',
    'register': 'Registration',
    'contacts': 'Contact us',
    'genres': 'All genres',
    'genre': 'Genre',
    'year': 'Movies from the',
    'rating': 'Movies by rating',
    'subscribe': 'Subscribing result'
}


class MovieList(ContextData, FilterView, ListView):
    model = Movie
    template_name = 'movie_app/main.html'
    context_object_name = 'movies'
    filterset_class = MovieFilter

    def get_queryset(self):
        # movies = cache.get('movies')
        # if not movies:
        #     movies = Movies.objects.filter(date_creation__lte=timezone.now()).select_related('genre')
        #     cache.set('movies', movies, 60)
        # return movies
        return self.model.objects\
            .filter(date_creation__lte=timezone.now())\
            .prefetch_related('genre')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MovieList, self).get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['main'])
        return context | context_data


class ShowMovie(ContextData, DetailView):
    model = Movie
    template_name = 'movie_app/movie.html'
    slug_url_kwarg = 'slug_movie'
    context_object_name = 'movie'

    def get_queryset(self):
        return self.model.objects.filter(date_creation__lte=timezone.now()).prefetch_related('genre')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=f"{context['movie'].title} ({context['movie'].year})")
        return context | context_data


class MovieByGenre(ContextData, FilterView):
    model = Movie
    template_name = 'movie_app/sorted_movies_by.html'
    context_object_name = 'movies'
    allow_empty = False
    filterset_class = MovieFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=f"{titles['genre']} \"{self.kwargs['slug_genre'].title()}\"")
        return context | context_data

    def get_queryset(self):
        order = self.request.GET.get('orderby', 'title')
        return self.model.objects\
            .filter(genre__slug=self.kwargs['slug_genre'])\
            .prefetch_related('genre')


class MovieByYear(ContextData, FilterView):
    model = Movie
    template_name = 'movie_app/sorted_movies_by.html'
    context_object_name = 'movies'
    allow_empty = False
    filterset_class = MovieFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=f"{titles['year']} \"{self.kwargs['year_movie']}\"")
        return context | context_data

    def get_queryset(self):
        return self.model.objects\
            .filter(year=self.kwargs['year_movie'])\
            .prefetch_related('genre')


class MovieByRating(ContextData, FilterView):
    model = Movie
    template_name = 'movie_app/sorted_movies_by.html'
    context_object_name = 'movies'
    allow_empty = False
    filterset_class = MovieFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=f"{titles['rating']} \"{self.kwargs['rating']}\"")
        return context | context_data

    def get_queryset(self):
        return self.model.objects\
            .filter(rating=self.kwargs['rating'])\
            .prefetch_related('genre')


class GenreList(ContextData, ListView):
    model = Genre
    template_name = 'movie_app/genre_list.html'
    context_object_name = 'genres'
    paginate_by = 0
    filterset_class = MovieFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['genres'])
        return context | context_data

    def get_queryset(self):
        return self.model.objects.all().annotate(Count('movie'))


class AddMovie(LoginRequiredMixin, ContextData, CreateView):
    form_class = AddMovieForm
    template_name = 'movie_app/add_movie.html'
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['add-movie'])
        return context | context_data


def about(request):
    context = {
        'title': titles['about'],
    }
    return render(request, 'movie_app/about.html', context)


class RegisterUser(ContextData, CreateView):
    form_class = RegisterUserForm
    template_name = 'movie_app/register.html'
    success_url = reverse_lazy('movie_app:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['register'])
        return context | context_data

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('movie_app:main')


class LoginUser(ContextData, LoginView):
    form_class = LoginUserForm
    template_name = 'movie_app/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['login'])
        return context | context_data

    def get_success_url(self):
        return reverse_lazy('movie_app:main')


def logout_user(request):
    logout(request)
    return redirect('movie_app:login')


class ContactFormView(ContextData, FormView):
    form_class = ContactForm
    template_name = 'movie_app/contact.html'
    success_url = reverse_lazy('movie_app:main')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['contacts'])
        return context | context_data

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('movie_app:main')


class SubscribeView(CreateView):
    form_class = SubscribeForm
    model = Subscribe
    success_url = reverse_lazy('movie_app:subscribe')
    template_name = 'movie_app/subscribe_done.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = titles['subscribe']
        return context

movie_app/templates/movie_app/about.html
{% extends 'movie_app/base.html' %}

{% block content %}
    <div class="mt-4 row">
        <div class="col">
            <h1>{{ title }}</h1>
        </div>
    </div>
{% endblock %}

movie_app/templates/movie_app/add_movie.html
{% extends 'movie_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="mt-4 row">
        <div class="col">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-0 col-md-0 col-md-4 col-lg-4">
        </div>
        <div class="col-12 col-md-12 col-md-8 col-lg-8">
            <form action="{% url 'movie_app:add-movie' %}" method="post" enctype="multipart/form-data">
                <div class="row">
                    {% csrf_token %}
                    <div class="col-12">
                        {% for field in form %}
                            {% if field.name in 'title slug description' %}
                                <div class="mb-3">
                                    {{ field|as_crispy_field }}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="row">
                    {% for field in form %}
                        {% if field.name in 'cover year rating genre' %}
                            <div class="col-6 col-xs-12">
                                <div class="mb-3">
                                    {{ field|as_crispy_field }}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="row">
                    {% for field in form %}
                        {% if field.name in 'captcha' %}
                            <div class="col-12">
                                <div class="mb-3">
                                    {{ field|as_crispy_field }}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <button class="btn btn-primary" type="submit">Add movie</button>
            </form>
        </div>
    </div>
{% endblock %}

movie_app/templates/movie_app/base.html
{% load static %}
{% load movies_app_tags %}

<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Meta tags -->
    <meta charset="UTF-8">

    <!-- Bootstrap CSS & JS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">

    <!-- Additional CSS & JS -->
    <link rel="stylesheet" href="{% static 'movie_app/css/custom.css' %}">

    {% block additional_css %}{% endblock %}
    <title>{{ title }}</title>
</head>
<body>
{% show_top_menu %}
<div class="container">
    {% block content %}
    {% endblock %}
    {% include 'includes/movie_app/pagination.html' %}
</div>
{% include 'includes/movie_app/footer.html' %}

<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>


<!-- Additional JS -->

</body>
</html>

movie_app/templates/movie_app/contact.html
{% extends 'movie_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="mt-4 row">
        <div class="col">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-0 col-md-0 col-md-4 col-lg-4">
        </div>
        <div class="col-12 col-md-12 col-md-8 col-lg-8">
            <form method="post">
                <div class="row">
                    {% csrf_token %}
                    <p class="invalid-feedback">
                        <strong>
                            {{ form.non_field_errors }}
                        </strong>
                    </p>
                    <div class="col-12">
                        {% for field in form %}
                                {#                            {% if field.name in 'title slug description' %}#}
                                <div class="mb-3">
                                    {{ field|as_crispy_field }}
                                </div>
                                {#                            {% endif %}#}
                        {% endfor %}
                    </div>
                </div>
                {#                <div class="row">#}
                {#                    {% for field in form %}#}
                {#                        {% if field.name in 'cover year rating genre' %}#}
                {#                            <div class="col-6 col-xs-12">#}
                {#                                <div class="mb-3">#}
                {#                                    {{ field|as_crispy_field }}#}
                {#                                </div>#}
                {#                            </div>#}
                {#                        {% endif %}#}
                {#                    {% endfor %}#}
                {#                </div>#}
                <button class="btn btn-primary" type="submit">Send!</button>
            </form>
        </div>
    </div>
{% endblock %}

movie_app/templates/movie_app/genre_list.html
{% extends 'movie_app/base.html' %}

{% block content %}
    <div class="mt-4 row">
        <div class="col">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-8 col-lg-6 col-xl-6">
            <ul class="list-group list-group-flush">
                {% for genre in genres.all %}
                    {% if genre.movie__count %}
                        <li class="list-group-item list-group-item-action">
                            <div class="d-flex w-100 justify-content-between">
                                <a href="{{ genre.get_absolute_url }}">
                                    <h5 class="mb-1">
                                        {{ genre.name }}
                                    </h5>
                                </a>
                                <a class="btn btn-sm btn-outline-warning text-dark"
                                   href="{{ genre.get_absolute_url }}">
                                        {{ genre.movie__count }}
                                </a>
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

movie_app/templates/movie_app/login.html
{% extends 'movie_app/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="mt-4 row">
        <div class="col">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-0 col-md-0 col-md-4 col-lg-4">
        </div>
        <div class="col-12 col-md-12 col-md-8 col-lg-8">
            <form method="post">
                <div class="row">
                    {% csrf_token %}
                    <div class="col-12">
                        <p class="invalid-feedback">
                            <strong>
                                {{ form.non_field_errors }}
                            </strong>
                        </p>
                        {% for field in form %}
                            {#                            {% if field.name in 'title slug description' %}#}
                            <div class="mb-3">
                                {{ field|as_crispy_field }}
                            </div>
                            {#                            {% endif %}#}
                        {% endfor %}
                    </div>
                </div>
                {#                <div class="row">#}
                {#                    {% for field in form %}#}
                {#                        {% if field.name in 'cover year rating genre' %}#}
                {#                            <div class="col-6 col-xs-12">#}
                {#                                <div class="mb-3">#}
                {#                                    {{ field|as_crispy_field }}#}
                {#                                </div>#}
                {#                            </div>#}
                {#                        {% endif %}#}
                {#                    {% endfor %}#}
                {#                </div>#}
                <button class="btn btn-primary" type="submit">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

movie_app/templates/movie_app/main.html
{% extends 'movie_app/base.html' %}

{% block content %}
    <div class="mt-4 row">
        <div class="col">
            <h1>
                {{ title }}
            </h1>
        </div>
    </div>
    <div class="row">
        {% include 'includes/movie_app/movie_list.html' %}
    </div>
{% endblock %}

movie_app/templates/movie_app/movie.html
{% extends 'movie_app/base.html' %}

{% load movies_app_tags %}
{% load static %}

{% block content %}
    <div class="mt-4 row">
        <div class="col d-flex justify-content-between align-items-center">
            <h1>Info about movie "{{ movie.title }}"</h1>
            <div class="dropstart">
                <a class="share btn btn-outline-warning border-0 dropdown-toggle"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">
                    <svg class="share-icon"
                         xmlns="http://www.w3.org/2000/svg"
                         viewBox="0 0 24 24"
                         width="24px"
                         height="24px">
                        <path d="M 18 2 C 16.35499 2 15 3.3549904 15 5 C 15 5.1909529 15.021791 5.3771224 15.056641 5.5585938 L 7.921875 9.7207031 C 7.3985399 9.2778539 6.7320771 9 6 9 C 4.3549904 9 3 10.35499 3 12 C 3 13.64501 4.3549904 15 6 15 C 6.7320771 15 7.3985399 14.722146 7.921875 14.279297 L 15.056641 18.439453 C 15.021555 18.621514 15 18.808386 15 19 C 15 20.64501 16.35499 22 18 22 C 19.64501 22 21 20.64501 21 19 C 21 17.35499 19.64501 16 18 16 C 17.26748 16 16.601593 16.279328 16.078125 16.722656 L 8.9433594 12.558594 C 8.9782095 12.377122 9 12.190953 9 12 C 9 11.809047 8.9782095 11.622878 8.9433594 11.441406 L 16.078125 7.2792969 C 16.60146 7.7221461 17.267923 8 18 8 C 19.64501 8 21 6.6450096 21 5 C 21 3.3549904 19.64501 2 18 2 z M 18 4 C 18.564129 4 19 4.4358706 19 5 C 19 5.5641294 18.564129 6 18 6 C 17.435871 6 17 5.5641294 17 5 C 17 4.4358706 17.435871 4 18 4 z M 6 11 C 6.5641294 11 7 11.435871 7 12 C 7 12.564129 6.5641294 13 6 13 C 5.4358706 13 5 12.564129 5 12 C 5 11.435871 5.4358706 11 6 11 z M 18 18 C 18.564129 18 19 18.435871 19 19 C 19 19.564129 18.564129 20 18 20 C 17.435871 20 17 19.564129 17 19 C 17 18.435871 17.435871 18 18 18 z"/>
                    </svg>
                </a>
                <ul class="share dropdown-menu w-50 border-warning">
                    {% include 'includes/movie_app/social_share.html' %}
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-8 col-md-6 col-md-6 col-lg-4">
            {% if movie.cover %}
                <a title="{{ movie.title }}'s cover" href="{{ movie.get_absolute_url }}">
                    <img class="img-thumbnail" src="{{ movie.cover.url }}" alt="{{ movie.title }} cover">
                </a>
            {% endif %}
        </div>
        <div class="col-8 col-md-6 col-md-6 col-lg-4">
            <div class="col-auto">
                <div class="col-auto">
                    <p></p>
                    <p>
                        {% with parts=movie.description|slice_partitions:15 %}
                            <span>
                                {{ parts.first_part }}
                            </span>
                            <span class="collapse" id="filters">
                                {{ parts.second_part }}
                            </span>
                        {% endwith %}
                        <a href="#readMore" data-bs-toggle="collapse" data-bs-target="#filters"
                           role="button" aria-expanded="false" aria-controls="#filters"
                           id="readMoreLink">
                            <small id="readMore">Read more...</small>
                        </a>
                    </p>
                </div>
                <div class="col-auto">
                    <div>
                        <p class="btn-group btn-group align-items-baseline" role="group">
                            <a class="btn btn-outline-primary"
                               href="{% url 'movie_app:genres' %}">
                                Genre(s):
                            </a>
                            {% for genre in movie.genre.all %}
                                <a class="btn btn-outline-secondary"
                                   href="{% url 'movie_app:genre' genre.slug %}">
                                    {{ genre|default:'to be confirmed' }}
                                </a>
                            {% endfor %}
                        </p>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="btn-group mb-3 btn-group align-items-baseline" role="group">
                        <a class="btn btn-outline-primary"
                           href="{% url 'movie_app:rating' movie.rating %}"
                           title="Show all movies with rating {{ movie.rating }}">
                            Rating IMDB:
                        </a>
                        <a class="btn btn-outline-secondary"
                           href="{% url 'movie_app:rating' movie.rating %}"
                           title="Show all movies with rating {{ movie.rating }}">
                            {{ movie.rating|default:'to be confirmed' }}
                        </a>
                    </div>
                </div>
                <div class="col-auto">
                    <div class="btn-group mb-3 btn-group align-items-baseline" role="group">
                        <a class="btn btn-outline-primary"
                           href="{% url 'movie_app:year' movie.year %}"
                           title="Show all movies from {{ movie.year }}">
                            Release year:
                        </a>
                        <a class="btn btn-outline-secondary"
                           href="{% url 'movie_app:year' movie.year %}"
                           title="Show all movies from {{ movie.year }}">
                            {{ movie.year|default:'to be confirmed' }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'movie_app/js/readMoreTextChanger.js' %}"></script>
{% endblock %}

movie_app/templates/movie_app/sorted_movies_by.html
{% extends 'movie_app/base.html' %}

{% load static %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'movie_app/css/custom.css' %}">
{% endblock %}

{% block content %}
    <div class="mt-4 row">
        <div class="col">
            <h1>{{ title }}</h1>
        </div>
    </div>
    <div class="row">
        {% include 'includes/movie_app/movie_list.html' %}
    </div>
{% endblock %}

movie_app/templates/movie_app/subscribe_done.html
{% extends 'movie_app/base.html' %}

{% block content %}
    {% if not form.errors %}
        <div class="m-4 row">
            <h4 class="text-success">
                You have subscribed successful!
            </h4>
        </div>
    {% else %}
        <div class="m-4 row">
            <div class="m-3">
                {% for non_field_error in form.non_field_errors %}
                    {{ non_field_error }}
                {% endfor %}
                {% for error in form.errors.values %}
                    {{ error }}
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}