Movies/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Movies import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls'), name='movie-app-index'),
    path(r'captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__', include('debug_toolbar.urls')),]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

movie_app/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.views.decorators.cache import cache_page

from Movies import settings
from .views import *

app_name = 'movie_app'
urlpatterns = [
    path('', MovieList.as_view(), name='main'),
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('movie/<slug:slug_movie>', ShowMovie.as_view(), name='movie'),
    path('year/<int:year_movie>', MovieByYear.as_view(), name='year'),
    path('genre/<slug:slug_genre>', MovieByGenre.as_view(), name='genre'),
    path('rating/<int:rating>', MovieByRating.as_view(), name='rating'),
    path('genres/', GenreList.as_view(), name='genres'),
    path('add-movie/', AddMovie.as_view(), name='add-movie'),
    path('about/', about, name='about'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('contacts/', ContactFormView.as_view(), name='contact-us'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_app/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Movie(models.Model):
    title = models.CharField(max_length=255, verbose_name='Movie title')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    description = models.TextField()
    cover = models.ImageField(upload_to='covers/%Y/%m/%d')
    year = models.IntegerField()
    rating = models.IntegerField()
    genre = models.ManyToManyField('Genre')
    date_creation = models.DateTimeField(verbose_name='Creation date', auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'All movies'
        verbose_name_plural = 'All movies'
        ordering = ('title', 'year',)

    def __str__(self):
        return f'{self.title}, {self.year}'

    def get_absolute_url(self):
        return reverse('movie_app:movie', kwargs={'slug_movie': self.slug})

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.date_creation <= now


class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'
        ordering = ('name',)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('movie_app:genre', kwargs={'slug_genre': self.slug})


def auto_incrementor():
    last_int = MenuItem.objects.all().order_by('position').last()
    if not last_int:
        return 1
    return last_int.position + 1


class MenuItem(models.Model):
    title = models.CharField(max_length=128)
    slug = models.SlugField(max_length=155, unique=True, verbose_name='URL')
    position = models.PositiveIntegerField(default=auto_incrementor,)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ('position',)
        verbose_name = 'Menu item'
        verbose_name_plural = 'Menu items'


class ContactUsData(models.Model):
    name = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    email = models.EmailField()
    content = models.TextField()

    def __str__(self):
        return f'From {self.name}, {self.email};\nsubject:\n{self.subject}'

    class Meta:
        ordering = ('name',)
        verbose_name = 'Contact us message'
        verbose_name_plural = 'Contact us messages'


class Subscribe(models.Model):
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True, verbose_name='Is subscribed')
    date_subscribe = models.DateTimeField(auto_now_add=True, verbose_name='Subscribe date')
    date_unsubscribe = models.DateTimeField(null=True, verbose_name='Unsubscribe date')

    def __str__(self):
        return self.email

    class Meta:
        ordering = ('email',)
        verbose_name = 'Subscriber'
        verbose_name_plural = 'Subscribers'


class FavoriteMovie(models.Model):
    pass
    # TODO

movie_app/forms.py
import datetime

from captcha.fields import CaptchaField
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import *
from crispy_forms.helper import FormHelper


class AddMovieForm(forms.ModelForm):
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['genre'].empty_label = '< Choose genre(s) >'
        self.helper = FormHelper()

    class Meta:
        model = Movie
        fields = ['title', 'slug', 'description', 'year', 'cover', 'rating', 'genre']

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 255:
            raise ValidationError('Length is more than 255 symbols.')
        return title

    def clean_year(self):
        year = self.cleaned_data['year']
        now = datetime.datetime.now().year + 1
        if not 1878 >= year >= now:
            raise ValidationError(f'Year may be after 1878 and before {now} inclusive.')
        return year

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        if not 0 >= rating >= 100:
            raise ValidationError(f'Rating may be from 0 to 100.')
        return rating


class RegisterUserForm(UserCreationForm):
    captcha = CaptchaField()
    email = forms.CharField(max_length=255, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    def clean_email(self):
        email = self.cleaned_data['email']
        is_exists = User.objects.filter(email=email)
        if is_exists:
            raise ValidationError(f'User with email "{email}" already exists.')
        return email

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    class Meta:
        model = User


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    class Meta:
        model = ContactUsData
        fields = ['subject', 'content', 'name', 'email']


class SubscribeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()

    def clean_email(self):
        email = self.cleaned_data['email']
        is_exists = Subscribe.objects.filter(email=email)
        if is_exists:
            raise ValidationError(f'Your email "{email}" is already subscribed!')
        return email

    class Meta:
        model = Subscribe
        fields = ['email']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control',
                                            'id': 'newsletter',
                                            'onchange': 'this.form.submit()',
                                            'placeholder': 'Your email...'})
        }
        labels = {
            'email': ''
        }

movie_app/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.db.models import Count
from django.http import HttpResponseRedirect, QueryDict
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django_filters.views import FilterView

from .filters import MovieFilter
from .models import *
from .forms import *
from .utils import *

titles = {
    'main': 'All movies',
    'add-movie': 'Add movie',
    'about': 'About',
    'login': 'Log in',
    'register': 'Registration',
    'contacts': 'Contact us',
    'genres': 'All genres',
    'genre': 'Genre',
    'year': 'Movies from the',
    'rating': 'Movies by rating',
    'subscribe': 'Subscribing result'
}


class MovieList(ContextData, FilterView, ListView):
    model = Movie
    template_name = 'movie_app/main.html'
    context_object_name = 'movies'
    filterset_class = MovieFilter

    def get_queryset(self):
        # movies = cache.get('movies')
        # if not movies:
        #     movies = Movies.objects.filter(date_creation__lte=timezone.now()).select_related('genre')
        #     cache.set('movies', movies, 60)
        # return movies
        return self.model.objects\
            .filter(date_creation__lte=timezone.now())\
            .prefetch_related('genre')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MovieList, self).get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['main'])
        return context | context_data


class ShowMovie(ContextData, DetailView):
    model = Movie
    template_name = 'movie_app/movie.html'
    slug_url_kwarg = 'slug_movie'
    context_object_name = 'movie'

    def get_queryset(self):
        return self.model.objects.filter(date_creation__lte=timezone.now()).prefetch_related('genre')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=f"{context['movie'].title} ({context['movie'].year})")
        return context | context_data


class MovieByGenre(ContextData, FilterView):
    model = Movie
    template_name = 'movie_app/sorted_movies_by.html'
    context_object_name = 'movies'
    allow_empty = False
    filterset_class = MovieFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=f"{titles['genre']} \"{self.kwargs['slug_genre'].title()}\"")
        return context | context_data

    def get_queryset(self):
        order = self.request.GET.get('orderby', 'title')
        return self.model.objects\
            .filter(genre__slug=self.kwargs['slug_genre'])\
            .prefetch_related('genre')


class MovieByYear(ContextData, FilterView):
    model = Movie
    template_name = 'movie_app/sorted_movies_by.html'
    context_object_name = 'movies'
    allow_empty = False
    filterset_class = MovieFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=f"{titles['year']} \"{self.kwargs['year_movie']}\"")
        return context | context_data

    def get_queryset(self):
        return self.model.objects\
            .filter(year=self.kwargs['year_movie'])\
            .prefetch_related('genre')


class MovieByRating(ContextData, FilterView):
    model = Movie
    template_name = 'movie_app/sorted_movies_by.html'
    context_object_name = 'movies'
    allow_empty = False
    filterset_class = MovieFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=f"{titles['rating']} \"{self.kwargs['rating']}\"")
        return context | context_data

    def get_queryset(self):
        return self.model.objects\
            .filter(rating=self.kwargs['rating'])\
            .prefetch_related('genre')


class GenreList(ContextData, ListView):
    model = Genre
    template_name = 'movie_app/genre_list.html'
    context_object_name = 'genres'
    paginate_by = 0
    filterset_class = MovieFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['genres'])
        return context | context_data

    def get_queryset(self):
        return self.model.objects.all().annotate(Count('movie'))


class AddMovie(LoginRequiredMixin, ContextData, CreateView):
    form_class = AddMovieForm
    template_name = 'movie_app/add_movie.html'
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['add-movie'])
        return context | context_data


def about(request):
    context = {
        'title': titles['about'],
    }
    return render(request, 'movie_app/about.html', context)


class RegisterUser(ContextData, CreateView):
    form_class = RegisterUserForm
    template_name = 'movie_app/register.html'
    success_url = reverse_lazy('movie_app:login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['register'])
        return context | context_data

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('movie_app:main')


class LoginUser(ContextData, LoginView):
    form_class = LoginUserForm
    template_name = 'movie_app/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['login'])
        return context | context_data

    def get_success_url(self):
        return reverse_lazy('movie_app:main')


def logout_user(request):
    logout(request)
    return redirect('movie_app:login')


class ContactFormView(ContextData, FormView):
    form_class = ContactForm
    template_name = 'movie_app/contact.html'
    success_url = reverse_lazy('movie_app:main')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context_data = self.get_user_context(title=titles['contacts'])
        return context | context_data

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('movie_app:main')


class SubscribeView(CreateView):
    form_class = SubscribeForm
    model = Subscribe
    success_url = reverse_lazy('movie_app:subscribe')
    template_name = 'movie_app/subscribe_done.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = titles['subscribe']
        return context

movie_app/templates/includes/movie_app/filter.html
{% load crispy_forms_tags %}

<div class="row mt-2 mb-4">
    <div class="col col-md-8">
        <div class="filters-header d-flex nowrap justify-content-start align-items-center
                    p-3 text-secondary navbar-light
                    border border-1 rounded mb-2"
             data-bs-toggle="collapse" data-bs-target="#filters"
             role="button" aria-expanded="false" aria-controls="#filters">
            <button class="me-3 border rounded bg-white">
                <span class="navbar-toggler-icon"></span>
            </button>
            <h5 class="mb-0">Filters & Sorting</h5>
        </div>
        <div class="collapse bg-light border rounded" id="filters">
            <form method="get">
                <div class="filters-form d-flex p-2 w-100 justify-content-between flex-wrap
                            text-secondary border border-light rounded-bottom">
                    {{ filter.form|crispy }}
                    <input class="btn btn-outline-dark mt-3 align-self-end" type="submit"/>
                </div>
            </form>
        </div>
    </div>
</div>

movie_app/templates/includes/movie_app/footer.html
{% load static %}

{% load movies_app_tags %}

<div class="container">
    <footer class="p-3 my-4 bg-white">
        <div class="row d-flex flex-wrap justify-content-between align-items-center
        mt-2 mb-4 text-muted">
            <div class="col-6">
                <ul class="nav flex-row">
                    {% for item in menu_items %}
                        {% concat_all 'movie_app:' item.slug as item_url %}
                        <li class="nav-item me-3">
                            <a href="{% url item_url %}" class="nav-link p-0 text-muted">{{ item }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="col-5">
                {% subscribe_form %}
            </div>
        </div>

        <div class="row p-3 d-flex flex-wrap justify-content-between
        align-items-center border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-decoration-none lh-1">
                    <img class="bg-white border-white rounded-2"
                         src="{% static 'movie_app/img/brand-logo.png' %}"
                         alt="All movies logo"
                         width="50px">
                </a>
                <span class="text-muted">&copy; 2022 All movies. All rights reserved.</span>
            </div>
            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                {% include 'includes/movie_app/social_share.html' %}
            </ul>
        </div>
    </footer>
</div>

movie_app/templates/includes/movie_app/movie_list.html
{% include 'includes/movie_app/filter.html' %}

<div class="row" id="movie-list">
    <div class="col col-md-8">
        {% if movies %}
            <ul class="list-group list-group-flush">
                {% for movie in movies %}
                    <li class="list-group-item list-group-item-action">
                        <div class="d-flex justify-content-between">
                            <div class="d-flex justify-content-start wrap">
                                <a href="{{ movie.get_absolute_url }}"
                                   title="View more about {{ movie.title }}">
                                    <div>
                                        {% if movie.cover %}
                                            <img class="card-img"
                                                 src="{{ movie.cover.url }}"
                                                 alt="{{ movie.title }}'s cover">
                                        {% endif %}
                                    </div>
                                </a>
                                <div>
                                    <a href="{{ movie.get_absolute_url }}"
                                       title="View more about {{ movie.title }}">
                                        <h5 class="mb-1">
                                            {{ movie.title }}
                                        </h5>
                                    </a>
                                    <div class="btn-group-sm btn-group align-items-baseline" role="group">
                                        {% for genre in movie.genre.all %}
                                            <a class="btn btn-outline-light text-dark"
                                               href="{{ genre.get_absolute_url }}"
                                               title="Show all {{ genre|title }} movies">
                                                <small class="mb-1">
                                                    {{ genre }}
                                                </small>
                                            </a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                            <div class="d-flex align-items-baseline">
                                {% if movie.rating and movie.rating < 40 %}
                                    <a class="btn btn-sm btn-outline-danger"
                                       href="{% url 'movie_app:rating' movie.rating %}"
                                       title="Show all movies with rating {{ movie.rating }}">
                                        {{ movie.rating }}
                                    </a>
                                {% elif 40 <= movie.rating and movie.rating < 60 %}
                                    <a class="btn btn-sm btn-outline-warning"
                                       href="{% url 'movie_app:rating' movie.rating %}"
                                       title="Show all movies with rating {{ movie.rating }}">
                                        {{ movie.rating }}
                                    </a>
                                {% elif 60 <= movie.rating and movie.rating < 85 %}
                                    <a class="btn btn-sm btn-outline-info"
                                       href="{% url 'movie_app:rating' movie.rating %}"
                                       title="Show all movies with rating {{ movie.rating }}">
                                        {{ movie.rating }}
                                    </a>
                                {% elif 85 <= movie.rating and movie.rating <= 100 %}
                                    <a class="btn btn-sm btn-outline-success"
                                       href="{% url 'movie_app:rating' movie.rating %}"
                                       title="Show all movies with rating {{ movie.rating }}">
                                        {{ movie.rating }}
                                    </a>
                                {% endif %}        &nbsp;
                                <a class="btn btn-sm btn-outline-warning text-dark"
                                   href="{% url 'movie_app:year' movie.year %}"
                                   title="Show all movies from {{ movie.year }}">
                                    {{ movie.year }}
                                </a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <h5 class="mb-1">No movies are available.</h5>
        {% endif %}
    </div>
</div>

movie_app/templates/includes/movie_app/navbar.html
{% load static %}

{% load movies_app_tags %}

<div class="row">
    <div class="col">
        <nav class="navbar navbar-expand-md navbar navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'movie_app:main' %}"
                   title="Main page">
                    <img class="bg-white border-dark rounded-2"
                         src="{% static 'movie_app/img/brand-logo.png' %}"
                         alt="All movies logo"
                         width="80px">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        {% for item in menu_items %}
                            {% if not forloop.last %}
                                <li class="nav-item">
                                    {% concat_all 'movie_app:' item.slug as item_url %}
                                    <a class="nav-link text-white" href="{% url item_url %}" title="{{ item.title }}">
                                        {{ item.title }}
                                    </a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                    <ul class="navbar-nav mr-auto">
                        {% if not request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link register btn btn-outline-light text-white"
                                   href="{% url 'movie_app:register' %}"
                                   title="Register">
                                    Register
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link login btn btn-outline-warning text-white"
                                   href="{% url 'movie_app:login' %}"
                                   title="Login">
                                    Login
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link login btn btn-outline-primary text-white" href="#"
                                   title="{{ user.username }} profile">
                                    {{ user.username }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link logout btn btn-outline-light text-white"
                                   href="{% url 'movie_app:logout' %}"
                                   title="Logout">
                                    Logout
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
</div>

movie_app/templates/includes/movie_app/pagination.html
{% load movies_app_tags %}

{% if page_obj.has_other_pages %}
    <div class="row mt-3">
        <div class="col">
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?{% url_replace request 'page' 1 %}" title="First page">
                                &laquo;
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link"
                               href="?{% url_replace request 'page' page_obj.previous_page_number %}"
                               title="Previous page">
                                &lsaquo;
                            </a>
                        </li>
                        {% if page_obj.number|add:"-2" > 1 %}
                            <li class="page-item">
                                <a class="page-link">
                                    ...
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                    {% for page in paginator.page_range %}
                        {% if page_obj.number == page %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?{% url_replace request 'page' page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% elif page >= page_obj.number|add:"-2" and page <= page_obj.number|add:"2" %}
                            <li class="page-item">
                                <a class="page-link" href="?{% url_replace request 'page' page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        {% if page_obj.number|add:"2" < page_obj.paginator.num_pages %}
                            <li class="page-item">
                                <a class="page-link">
                                    ...
                                </a>
                            </li>
                        {% endif %}
                        <li class="page-item">
                            <a class="page-link"
                               href="?{% url_replace request 'page' page_obj.next_page_number %}"
                               title="Next page">
                                &rsaquo;
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link"
                               href="?{% url_replace request 'page' page_obj.paginator.num_pages %}"
                               title="Last page">
                                &raquo;
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}

movie_app/templates/includes/movie_app/social_share.html
{% include 'includes/movie_app/svg_sprite_icons.html' %}

<li class="m-3"><a class="social"
                    href="http://vk.com/share.php?url=127.0.0.1/{{ movie.get_absolute_url }}"
                    target="_blank" rel="nofollow">
    <svg class="bi" width="32" height="32">
        <use xlink:href="#icon-vk"/>
    </svg>
</a></li>
<li class="m-3"><a class="social"
                    href="https://twitter.com/share?url=127.0.0.1/{{ movie.get_absolute_url }}"
                    target="_blank" rel="nofollow">
    <svg class="bi" width="32" height="32">
        <use xlink:href="#twitter"/>
    </svg>
</a></li>
<li class="m-3"><a class="social"
                    href="https://www.facebook.com/sharer/sharer.php?u=127.0.0.1/{{ movie.get_absolute_url }}"
                    target="_blank" rel="nofollow">
    <svg class="bi" width="32" height="32">
        <use xlink:href="#facebook"/>
    </svg>
</a></li>
<li class="m-3"><a class="social"
                    href="https://www.instagram.com/?url=127.0.0.1/{{ movie.get_absolute_url }}"
                    target="_blank" rel="noopener">
    <svg class="bi" width="32" height="32">
        <use xlink:href="#instagram"/>
    </svg>
</a></li>